name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project
        run: mvn clean package

      - name: Upload jar to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/task-tracker-cli-1.0-SNAPSHOT.jar
